import { scheduleDataInitialState } from "./schedule-data/schedule-data-initial-state";
import {
  createActionName,
  isScheduleAction,
  ScheduleActionModel,
  ScheduleActionType,
} from "./schedule-data/schedule.actions";

export function generationInfoReducerF(name: string) {
  return (
    state: boolean = scheduleDataInitialState.isAutoGenerated,
    action: ScheduleActionModel
  ): boolean => {
    switch (action.type) {
      case createActionName(name, ScheduleActionType.ADD_NEW):
      case createActionName(name, ScheduleActionType.UPDATE):
        if (!isScheduleAction(action)) {
          return state;
        }
        return action.payload?.isAutoGenerated ?? true;
      default:
        return state;
    }
  };
}
