/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/. */
import ErrorOutlineIcon from "@material-ui/icons/ErrorOutline";
import React, { useEffect } from "react";
import { useDispatch, useSelector } from "react-redux";
import { useHistory } from "react-router-dom";
import {
  ButtonData,
  DropdownButtons
} from "../../../components/buttons/dropdown-buttons/dropdown-buttons.component";
import { ImportButtonsComponent } from "../../../components/buttons/import-buttons/import-buttons.component";
import { Button } from "../../../components/common-components";
import { t } from "../../../helpers/translations.helper";
import { VerboseDateHelper } from "../../../helpers/verbose-date.helper";
import {
  RevisionTypeLabels
} from "../../../logic/data-access/persistance-store.model";
import { changeRevision } from "../../../state/schedule-data/schedule-condition/revision-info.reducer";
import { AlgorithmErrorCode } from "../../../state/schedule-data/schedule-errors/schedule-error.model";
import {
  getActualRevision,
  getPresentScheduleIsAutogenerated,
  getPresentScheduleIsCorrupted,
  getPresentTemporaryScheduleInfo,
  getScheduleErrors
} from "../../../state/schedule-data/selectors";
import * as S from "./read-only-toolbar.styled";

interface ViewOnlyToolbarOptions {
  openEdit: () => void;
}
export function ReadOnlyToolbar({ openEdit }: ViewOnlyToolbarOptions): JSX.Element {
  const [isEditDisable, setEditDisable] = React.useState(false);
  const [isMonthFromFuture, setIsMonthFromFuture] = React.useState(false);
  const [areAlgoErrorsPresent, setAreAlgoErrorsPresent] = React.useState(false);
  const dispatch = useDispatch();
  const history = useHistory();

  const { year, month_number: month } = useSelector(getPresentTemporaryScheduleInfo);

  const isAutoGenerated = useSelector(getPresentScheduleIsAutogenerated);

  const isCorrupted = useSelector(getPresentScheduleIsCorrupted);

  const revision = useSelector(getActualRevision);

  const scheduleErrors = useSelector(getScheduleErrors);

  useEffect(() => {
    const isFuture = VerboseDateHelper.isMonthInFuture(month, year);
    setIsMonthFromFuture(isFuture);

    const isRevisionEditDisable = revision === "actual" ? false : !isFuture;
    setEditDisable(isRevisionEditDisable || isCorrupted);

    setAreAlgoErrorsPresent(
      Object.values(AlgorithmErrorCode).some((errorCode) => errorCode in scheduleErrors)
    );
  }, [year, month, revision, isCorrupted, scheduleErrors]);

  const revisionButtons: ButtonData[] = [
    {
      dataCy: "primary-revision",
      label: t("primary"),
      action: () => dispatch(changeRevision("primary")),
    },
    {
      dataCy: "actual-revision",
      label: t("actual"),
      action: () => dispatch(changeRevision("actual")),
    },
  ];

  const onEditClick = (): void => {
    openEdit();
    history.push("/schedule-editing");
  };
  return (
    <>
      {!isAutoGenerated && (
        <S.Wrapper>
          <S.RevisionWrapper>
            {isMonthFromFuture ? (
              <p>{RevisionTypeLabels[revision]}</p>
            ) : (
              <DropdownButtons
                mainLabel={t(revision)}
                buttons={revisionButtons}
                data-cy="revision-select"
                buttonVariant="secondary"
                style={{ width: "250px" }}
              />
            )}
          </S.RevisionWrapper>
          {areAlgoErrorsPresent && (
            <S.ErrorPresentInfo className="errors-present-info">
              <ErrorOutlineIcon />
              <p>{t("scheduleHasErrors")}</p>
            </S.ErrorPresentInfo>
          )}
          <S.Filler />
          <ImportButtonsComponent />
          <Button
            onClick={onEditClick}
            size="small"
            variant="primary"
            data-cy="edit-mode-button"
            disabled={isEditDisable}
            style={{ marginLeft: "8px" }}
          >
            {t("edit")}
          </Button>
        </S.Wrapper>
      )}
    </>
  );
}
