module.exports = {
  "__version": "6.5.0",
  "Schedule errors": {
    "when errors are present": {
      "shows errors returned by server": {
        "1": [
          "Za mało pracowników w trakcie dnia: potrzeba 8, jest 5.",
          "Za mało pracowników w trakcie dnia: potrzeba 8, jest 0.",
          "Za mało pracowników w nocy: potrzeba 5, jest 0.",
          "16 niedogodzin",
          "64 niedogodziny",
          "112 niedogodziny",
          "160 niedogodzin"
        ]
      }
    }
  },
  "Copy schedule from previous month": {
    "when iterating through entire year": {
      "properly copies previous schedule": {
        "1": [
          "DN",
          "",
          "",
          "",
          "",
          "",
          "",
          "D",
          "R",
          "N",
          "",
          "D",
          "",
          "N",
          "",
          "N",
          "",
          "",
          "",
          "DN",
          "",
          "N",
          "N",
          "N",
          "N",
          "",
          "",
          "D",
          "N",
          "N",
          "",
          "",
          "DN",
          "PN",
          ""
        ],
        "2": [
          "N",
          "N",
          "",
          "",
          "DN",
          "PN",
          "",
          "D",
          "R",
          "N",
          "",
          "D",
          "",
          "N",
          "",
          "N",
          "",
          "",
          "",
          "DN",
          "",
          "N",
          "N",
          "N",
          "N",
          "",
          "",
          "D",
          "D",
          "R",
          "N",
          "",
          "D",
          "",
          "N"
        ],
        "3": [
          "D",
          "R",
          "N",
          "",
          "D",
          "",
          "N",
          "",
          "N",
          "",
          "",
          "",
          "DN",
          "",
          "N",
          "N",
          "N",
          "N",
          "",
          "",
          "D",
          "D",
          "R",
          "N",
          "",
          "D",
          "",
          "N"
        ],
        "4": [
          "D",
          "R",
          "N",
          "",
          "D",
          "",
          "N",
          "",
          "N",
          "",
          "",
          "",
          "DN",
          "",
          "N",
          "N",
          "N",
          "N",
          "",
          "",
          "D",
          "D",
          "R",
          "N",
          "",
          "D",
          "",
          "N",
          "D",
          "R",
          "N",
          "",
          "D",
          "",
          "N"
        ],
        "5": [
          "D",
          "R",
          "N",
          "",
          "D",
          "",
          "N",
          "D",
          "R",
          "N",
          "",
          "D",
          "",
          "N",
          "",
          "N",
          "",
          "",
          "",
          "DN",
          "",
          "N",
          "N",
          "N",
          "N",
          "",
          "",
          "D",
          "D",
          "R",
          "N",
          "",
          "D",
          "",
          "N"
        ],
        "6": [
          "D",
          "R",
          "N",
          "",
          "D",
          "",
          "N",
          "D",
          "R",
          "N",
          "",
          "D",
          "",
          "N",
          "",
          "N",
          "",
          "",
          "",
          "DN",
          "",
          "N",
          "N",
          "N",
          "N",
          "",
          "",
          "D",
          "D",
          "R",
          "N",
          "",
          "D",
          "",
          "N",
          "",
          "N",
          "",
          "",
          "",
          "DN",
          ""
        ],
        "7": [
          "",
          "N",
          "",
          "",
          "",
          "DN",
          "",
          "D",
          "R",
          "N",
          "",
          "D",
          "",
          "N",
          "",
          "N",
          "",
          "",
          "",
          "DN",
          "",
          "N",
          "N",
          "N",
          "N",
          "",
          "",
          "D",
          "D",
          "R",
          "N",
          "",
          "D",
          "",
          "N"
        ],
        "8": [
          "D",
          "R",
          "N",
          "",
          "D",
          "",
          "N",
          "D",
          "R",
          "N",
          "",
          "D",
          "",
          "N",
          "",
          "N",
          "",
          "",
          "",
          "DN",
          "",
          "N",
          "N",
          "N",
          "N",
          "",
          "",
          "D",
          "D",
          "R",
          "N",
          "",
          "D",
          "",
          "N"
        ],
        "9": [
          "D",
          "R",
          "N",
          "",
          "D",
          "",
          "N",
          "D",
          "R",
          "N",
          "",
          "D",
          "",
          "N",
          "",
          "N",
          "",
          "",
          "",
          "DN",
          "",
          "N",
          "N",
          "N",
          "N",
          "",
          "",
          "D",
          "D",
          "R",
          "N",
          "",
          "D",
          "",
          "N",
          "",
          "N",
          "",
          "",
          "",
          "DN",
          ""
        ],
        "10": [
          "",
          "N",
          "",
          "",
          "",
          "DN",
          "",
          "D",
          "R",
          "N",
          "",
          "D",
          "",
          "N",
          "",
          "N",
          "",
          "",
          "",
          "DN",
          "",
          "N",
          "N",
          "N",
          "N",
          "",
          "",
          "D",
          "D",
          "R",
          "N",
          "",
          "D",
          "",
          "N"
        ],
        "11": [
          "D",
          "R",
          "N",
          "",
          "D",
          "",
          "N",
          "D",
          "R",
          "N",
          "",
          "D",
          "",
          "N",
          "",
          "N",
          "",
          "",
          "",
          "DN",
          "",
          "N",
          "N",
          "N",
          "N",
          "",
          "",
          "D",
          "D",
          "R",
          "N",
          "",
          "D",
          "",
          "N"
        ],
        "12": [
          "D",
          "R",
          "N",
          "",
          "D",
          "",
          "N",
          "",
          "N",
          "",
          "",
          "",
          "DN",
          "",
          "N",
          "N",
          "N",
          "N",
          "",
          "",
          "D",
          "D",
          "R",
          "N",
          "",
          "D",
          "",
          "N",
          "D",
          "R",
          "N",
          "",
          "D",
          "",
          "N"
        ],
        "13": [
          "D",
          "R",
          "N",
          "",
          "D",
          "",
          "N",
          "D",
          "R",
          "N",
          "",
          "D",
          "",
          "N",
          "",
          "N",
          "",
          "",
          "",
          "DN",
          "",
          "N",
          "N",
          "N",
          "N",
          "",
          "",
          "D",
          "D",
          "R",
          "N",
          "",
          "D",
          "",
          "N"
        ]
      }
    }
  },
  "Shift range selection": {
    "Should be able to edit multiple days of single nurse (drag left to right)": {
      "1": [
        "",
        "",
        "",
        "L4",
        "",
        "",
        "",
        "",
        "U",
        "",
        "",
        "D",
        "",
        "R",
        "R",
        "",
        "",
        "D",
        "DN",
        "",
        "",
        "R",
        "R",
        "",
        "D",
        "",
        "",
        "",
        "",
        "D",
        "",
        "DN",
        "",
        "DN",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "D",
        "R",
        "N",
        "",
        "D",
        "",
        "N",
        "",
        "N",
        "",
        "",
        "",
        "DN",
        "",
        "N",
        "N",
        "N",
        "N",
        "",
        "",
        "D",
        "N",
        "N",
        "",
        "",
        "DN",
        "PN",
        "",
        "DN",
        "",
        "",
        "",
        "",
        "",
        ""
      ]
    },
    "Should be able to edit multiple days of single nurse (drag right to left)": {
      "1": [
        "",
        "",
        "",
        "",
        "",
        "",
        "U",
        "",
        "",
        "",
        "",
        "D",
        "",
        "R",
        "R",
        "",
        "",
        "D",
        "DN",
        "",
        "",
        "R",
        "R",
        "",
        "D",
        "",
        "",
        "",
        "",
        "D",
        "",
        "DN",
        "",
        "DN",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "D",
        "R",
        "N",
        "",
        "D",
        "",
        "N",
        "",
        "N",
        "",
        "",
        "",
        "DN",
        "",
        "N",
        "N",
        "N",
        "N",
        "",
        "",
        "D",
        "N",
        "N",
        "",
        "",
        "DN",
        "PN",
        "",
        "DN",
        "",
        "",
        "",
        "",
        "",
        ""
      ]
    },
    "Should be able to edit multiple single day of multiple nurses": {
      "1": [
        "",
        "",
        "",
        "",
        "",
        "",
        "U",
        "",
        "",
        "",
        "",
        "L4",
        "",
        "R",
        "R",
        "",
        "",
        "D",
        "DN",
        "",
        "",
        "R",
        "R",
        "",
        "D",
        "",
        "",
        "",
        "",
        "D",
        "",
        "DN",
        "",
        "DN",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "D",
        "R",
        "N",
        "",
        "L4",
        "",
        "N",
        "",
        "N",
        "",
        "",
        "",
        "DN",
        "",
        "N",
        "N",
        "N",
        "N",
        "",
        "",
        "D",
        "N",
        "N",
        "",
        "",
        "DN",
        "PN",
        "",
        "DN",
        "",
        "",
        "",
        "",
        "",
        ""
      ]
    },
    "Should be able to edit multiple days of single babysitter": {
      "1": [
        "L4",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "D",
        "N",
        "",
        "DN",
        "N",
        "",
        "D",
        "D",
        "",
        "",
        "D",
        "R",
        "DN",
        "N",
        "",
        "",
        "DN",
        "",
        "D",
        "N",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "N",
        "",
        "N",
        "N",
        "",
        "N",
        "",
        "D",
        "P",
        "N",
        "N",
        "",
        "",
        "",
        "D",
        "N",
        "N",
        "",
        "D",
        "N",
        "N",
        "N",
        "",
        "R",
        "N",
        "N",
        "",
        "D",
        "",
        "R",
        "",
        "",
        "",
        "",
        "",
        ""
      ]
    },
    "Should be able to edit multiple single day of multiple babysitters": {
      "1": [
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "N",
        "",
        "L4",
        "",
        "",
        "",
        "D",
        "N",
        "",
        "D",
        "N",
        "",
        "DN",
        "N",
        "",
        "D",
        "D",
        "",
        "",
        "D",
        "R",
        "DN",
        "N",
        "",
        "",
        "DN",
        "",
        "D",
        "N",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "N",
        "",
        "N",
        "L4",
        "",
        "",
        "",
        "D",
        "P",
        "N",
        "N",
        "",
        "",
        "",
        "D",
        "N",
        "N",
        "",
        "D",
        "N",
        "N",
        "N",
        "",
        "R",
        "N",
        "N",
        "",
        "D",
        "",
        "R",
        "",
        "",
        "",
        "",
        "",
        ""
      ]
    }
  },
  "ComparatorHelper": {
    "stableSort": {
      "ascending order": {
        "when sorting by complex type": {
          "does not change the array": {
            "1": [
              {
                "simpleType": 1,
                "complexType": {
                  "string": "x",
                  "number": 3
                }
              },
              {
                "simpleType": 3,
                "complexType": {
                  "string": "y",
                  "number": 1
                }
              },
              {
                "simpleType": 2,
                "complexType": {
                  "string": "z",
                  "number": 2
                }
              },
              {
                "simpleType": 2,
                "complexType": {
                  "string": "z1",
                  "number": 2
                }
              }
            ]
          }
        },
        "when sorting by simple type": {
          "sorts array in stable manner": {
            "1": [
              {
                "simpleType": 1,
                "complexType": {
                  "string": "x",
                  "number": 3
                }
              },
              {
                "simpleType": 2,
                "complexType": {
                  "string": "z",
                  "number": 2
                }
              },
              {
                "simpleType": 2,
                "complexType": {
                  "string": "z1",
                  "number": 2
                }
              },
              {
                "simpleType": 3,
                "complexType": {
                  "string": "y",
                  "number": 1
                }
              }
            ]
          }
        }
      },
      "descending order": {
        "when sorting by simple type": {
          "sorts array in stable manner": {
            "1": [
              {
                "simpleType": 3,
                "complexType": {
                  "string": "y",
                  "number": 1
                }
              },
              {
                "simpleType": 2,
                "complexType": {
                  "string": "z",
                  "number": 2
                }
              },
              {
                "simpleType": 2,
                "complexType": {
                  "string": "z1",
                  "number": 2
                }
              },
              {
                "simpleType": 1,
                "complexType": {
                  "string": "x",
                  "number": 3
                }
              }
            ]
          }
        }
      }
    }
  },
  "DataRowHelper": {
    "copyWithReplaced": {
      "when given boolean matrix and new value": {
        "changes values at set positions": {
          "1": [
            {
              "key": "test",
              "data": [
                0,
                12,
                13,
                0
              ],
              "isEditable": true
            },
            {
              "key": "test",
              "data": [
                21,
                0,
                23,
                0
              ],
              "isEditable": true
            }
          ]
        }
      }
    },
    "dataRowsAsValueDict": {
      "when data row's keys are the same": {
        "when include nulls is true": {
          "includes nulls in the output and squashes the rows": {
            "1": {
              "test": [
                21,
                22,
                null,
                24
              ]
            }
          }
        },
        "when include nulls is false": {
          "does not include nulls in the output and squashes the rows": {
            "1": {
              "test": [
                21,
                22,
                24
              ]
            }
          }
        }
      },
      "when data row's keys are not the same": {
        "when include nulls is true": {
          "includes nulls in the output": {
            "1": {
              "test": [
                11,
                12,
                13,
                null
              ],
              "test1": [
                21,
                22,
                null,
                24
              ]
            }
          }
        },
        "when include nulls is false": {
          "does not include nulls in the output": {
            "1": {
              "test": [
                11,
                12,
                13
              ],
              "test1": [
                21,
                22,
                24
              ]
            }
          }
        }
      }
    }
  }
}
