/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/. */
import { RevisionType, ThunkFunction } from "../../api/persistance-store.model";
import * as _ from "lodash";
import { cropScheduleDMToMonthDM } from "../../logic/schedule-container-convertion/schedule-container-convertion";
import { LocalStorageProvider } from "../../api/local-storage-provider.model";
import { Shift, ShiftCode } from "../../common-models/shift-info.model";
import { MonthDataModel, ScheduleDataModel } from "../../common-models/schedule-data.model";
import { VerboseDateHelper } from "../../helpers/verbose-date.helper";
import { ScheduleDataActionCreator } from "./month-state/schedule-data/schedule-data.action-creator";

export class ShiftsActionCreator {
  static deleteShift(shift: Shift | undefined): ThunkFunction<unknown> {
    return async (dispatch, getState): Promise<void> => {
      if (!shift) return;

      const { code } = shift;
      const actualSchedule = _.cloneDeep(getState().actualState.persistentSchedule.present);
      const actualMonth = cropScheduleDMToMonthDM(actualSchedule);

      const updatedMonth = ShiftsActionCreator.deleteShiftFromMonthDM(actualMonth, code);

      dispatch(this.createUpdateAction(updatedMonth));

      const nextMonthDM = await new LocalStorageProvider().getMonthRevision(
        actualMonth.scheduleKey.nextMonthKey.getRevisionKey("primary")
      );

      if (_.isNil(nextMonthDM) || !nextMonthDM.isAutoGenerated) return;
      const updatedNextMonth = ShiftsActionCreator.deleteShiftFromMonthDM(actualMonth, code);
      await new LocalStorageProvider().saveBothMonthRevisionsIfNeeded("primary", updatedNextMonth);
    };
  }

  private static deleteShiftFromMonthDM(
    monthDataModel: MonthDataModel,
    shiftCode: string
  ): MonthDataModel {
    const monthDataModelCopy = _.cloneDeep(monthDataModel);
    console.log(shiftCode);
    Object.entries(monthDataModelCopy.shifts).forEach(([workerName, workersShifts]) => {
      monthDataModelCopy.shifts[workerName] = workersShifts.map((shiftCodeInArray) =>
        shiftCodeInArray === shiftCode ? ShiftCode.W : shiftCodeInArray
      );
    });
    delete monthDataModelCopy.shift_types[shiftCode];
    console.log(monthDataModelCopy);
    return monthDataModelCopy;
  }

  private static createUpdateAction(
    updatedMonth: MonthDataModel
  ): ThunkFunction<ScheduleDataModel> {
    const { year, month } = updatedMonth.scheduleKey;
    const revision: RevisionType = VerboseDateHelper.isMonthInFuture(month, year)
      ? "primary"
      : "actual";

    return ScheduleDataActionCreator.setScheduleFromMonthDMAndSaveInDB(updatedMonth, revision);
  }
}
