/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/. */
import * as _ from "lodash";
import { SHIFTS } from "./shifts-types/shift-types.model";
import { ScheduleDataModel } from "./schedule-data.model";
import { workerShiftsInitialState } from "./workers-shifts/worker-shifts.initial-state";
import { workerInfoinitialState } from "./worker-info/worker-info.initial-state";
import { foundationInfoInitialState } from "./foundation-info/foundation-info.initial-state";
import { monthInfoInitialState } from "./month-info/month-info.initial-state";

export const scheduleDataInitialState: ScheduleDataModel = {
  schedule_info: monthInfoInitialState,
  month_info: foundationInfoInitialState,
  employee_info: workerInfoinitialState,
  shifts: workerShiftsInitialState,
  isAutoGenerated: true,
  shift_types: _.cloneDeep(SHIFTS),
  isCorrupted: false,
};
