/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/. */

/* eslint-disable @typescript-eslint/camelcase */
import { combineReducers } from "redux";
import { ScheduleDataModel } from "../models/common-models/schedule-data.model";
import { CombinedReducers } from "../app.reducer";
import { employeeInfoReducerF } from "./worker-info/employee-info.reducer";
import { monthInfoReducerF } from "./foundation-info/month-info.reducer";
import { scheduleInfoReducerF } from "./month-info/schedule-info.reducer";
import { scheduleShiftsInfoReducerF } from "./workers-shifts/shifts-info.reducer";
import { generationInfoReducerF } from "./schedule-condition/generation-info.reducer";
import { shiftsModelReducer } from "./shifts-types/shifts-model.reducer";
import { corruptedInfoReducerF } from "./schedule-condition/corrupted-info.reducer";

// eslint-disable-next-line @typescript-eslint/explicit-function-return-type
export function scheduleReducerF(name: string) {
  return combineReducers({
    schedule_info: scheduleInfoReducerF(name),
    shifts: scheduleShiftsInfoReducerF(name),
    month_info: monthInfoReducerF(name),
    employee_info: employeeInfoReducerF(name),
    isAutoGenerated: generationInfoReducerF(name),
    shift_types: shiftsModelReducer,
    isCorrupted: corruptedInfoReducerF(name),
  } as CombinedReducers<ScheduleDataModel>);
}
