/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/. */
import React from "react";
import { ScheduleComponentState } from "./table/schedule/schedule-state.model";
import { CorruptedScheduleComponent } from "./corrupted-schedule.component";
import { ScheduleComponent } from "./table/schedule/schedule.component";
import { useSelector } from "react-redux";
import { ApplicationStateModel } from "../../state/models/application-state.model";
import { NewScheduleComponent } from "./new-schedule.component";

interface ScheduleContainerOptions {
  schedule: ScheduleComponentState;
}

export function ScheduleContainerComponent({
  schedule: scheduleLocalState,
}: ScheduleContainerOptions): JSX.Element {
  const { isCorrupted } = useSelector(
    (state: ApplicationStateModel) => state.actualState.persistentSchedule.present
  );

  const isPresent =
    scheduleLocalState.isInitialized &&
    !scheduleLocalState.isAutoGenerated &&
    scheduleLocalState.dateSection?.length;

  return (
    <>
      {isPresent ? (
        isCorrupted ? (
          <CorruptedScheduleComponent />
        ) : (
          <ScheduleComponent schedule={scheduleLocalState} />
        )
      ) : (
        <NewScheduleComponent />
      )}
    </>
  );
}
