/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/. */
import * as _ from "lodash";
import React from "react";
import { useSelector } from "react-redux";
import {
  ApplicationStateModel,
  ScheduleStateModel,
} from "../../state/models/application-state.model";
import { NewScheduleComponent } from "./new-schedule.component";
import { ScheduleComponent } from "./table/schedule/schedule.component";
import { ScheduleMode } from "./table/schedule/schedule-state.model";

interface ScheduleContainerOptions {
  mode: ScheduleMode;
}

export function ScheduleContainerComponent({ mode }: ScheduleContainerOptions): JSX.Element {
  const key: keyof ScheduleStateModel =
    mode === ScheduleMode.Edit ? "temporarySchedule" : "persistentSchedule";

  const schedule = useSelector((state: ApplicationStateModel) => state.actualState[key].present);

  const isPresent =
    !_.isNil(schedule) && !schedule.isAutoGenerated && schedule.month_info.dates?.length;

  return <>{isPresent ? <ScheduleComponent /> : <NewScheduleComponent />}</>;
}
