/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/. */
import { createReducer } from "@reduxjs/toolkit";
import { ScheduleActionDestination } from "../../app.reducer";
import { scheduleDataInitialState } from "../schedule-data-initial-state";
import { addNewSchedule, isScheduleAction, updateSchedule } from "../schedule.actions";

export const generationInfoReducerF = (name: ScheduleActionDestination) =>
  createReducer(scheduleDataInitialState.isAutoGenerated, (builder) => {
    builder
      .addCase(addNewSchedule(name), (state, action) => {
        if (!isScheduleAction(action)) {
          return state;
        }
        return action.payload?.isAutoGenerated ?? true;
      })
      .addCase(updateSchedule(name), (state, action) => {
        if (!isScheduleAction(action)) {
          return state;
        }
        return action.payload?.isAutoGenerated ?? true;
      })
      .addDefaultCase((state) => state);
  });
